set(_AMENT_PACKAGE_NAME "ros2_frame")
set(ros2_frame_VERSION "0.0.0")
set(ros2_frame_MAINTAINER "admin <hh178239456@gmail.com>")
set(ros2_frame_BUILD_DEPENDS "rclcpp" "std_msgs" "ament_index_cpp")
set(ros2_frame_BUILDTOOL_DEPENDS "ament_cmake")
set(ros2_frame_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "ament_index_cpp")
set(ros2_frame_BUILDTOOL_EXPORT_DEPENDS )
set(ros2_frame_EXEC_DEPENDS "rclcpp" "std_msgs" "ament_index_cpp")
set(ros2_frame_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(ros2_frame_GROUP_DEPENDS )
set(ros2_frame_MEMBER_OF_GROUPS )
set(ros2_frame_DEPRECATED "")
set(ros2_frame_EXPORT_TAGS)
list(APPEND ros2_frame_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
